{{- if .Values.annotator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knightly.annotatorServiceAccountName" . }}
  labels:
    {{- include "knightly.annotatorLabels" . | nindent 4 }}
  {{- with .Values.annotator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
