apiVersion: v1
kind: Service
metadata:
  name: {{ include "knightly.commanderFullname" . }}
  labels:
    {{- include "knightly.commanderLabels" . | nindent 4 }}
spec:
  type: {{ .Values.commander.service.type }}
  ports:
    - port: {{ .Values.commander.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knightly.commanderSelectorLabels" . | nindent 4 }}
