{{- if .Values.commander.configMap.data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knightly.commanderFullname" . }}
  labels:
    {{- include "knightly.commanderLabels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.commander.configMap.data }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
