{{- if .Values.commander.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knightly.commanderServiceAccountName" . }}
  labels:
    {{- include "knightly.commanderLabels" . | nindent 4 }}
  {{- with .Values.commander.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
