apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knightly.commanderFullname" . }}
  labels:
    {{- include "knightly.commanderLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.commander.replicaCount }}
  selector:
    matchLabels:
      {{- include "knightly.commanderSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.commander.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "knightly.commanderSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.commander.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knightly.commanderServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.commander.podSecurityContext | nindent 8 }}
      containers:
        - name: commander
          securityContext:
            {{- toYaml .Values.commander.securityContext | nindent 12 }}
          image: "{{ .Values.commander.image.repository }}:{{ .Values.commander.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.commander.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.commander.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.commander.resources | nindent 12 }}
          {{- if .Values.commander.configMap.data }}
          envFrom:
            - configMapRef:
                name: {{ include "knightly.commanderFullname" . }}
          {{- end }}
      {{- with .Values.commander.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commander.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commander.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
