apiVersion: v1
kind: Service
metadata:
  name: {{ include "knightly.controllerFullname" . }}
  labels:
    {{- include "knightly.controllerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knightly.controllerSelectorLabels" . | nindent 4 }}
