apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "knightly.zeroScalerFullname" . }}
  labels:
    {{- include "knightly.zeroScalerLabels" . | nindent 4 }}
spec:
  schedule: {{ .Values.zeroScaler.cronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.zeroScaler.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "knightly.zeroScalerSelectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.zeroScaler.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "knightly.zeroScalerServiceAccountName" . }}
          securityContext:
            {{- toYaml .Values.zeroScaler.podSecurityContext | nindent 12 }}
          containers:
          - name: zero-scaler
            image: "{{ .Values.zeroScaler.image.repository }}:{{ .Values.zeroScaler.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.zeroScaler.image.pullPolicy }}
            securityContext:
              {{- toYaml .Values.zeroScaler.securityContext | nindent 14 }}
            {{- if .Values.zeroScaler.configMap.data }}
            envFrom:
              - configMapRef:
                  name: {{ include "knightly.zeroScalerFullname" . }}
            {{- end }}
          restartPolicy: {{ .Values.zeroScaler.cronJob.restartPolicy }}
